version: '3.8'

services:
  app:
    build: .
    container_name: pharmacy_app
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - pharmacy_net

  nginx:
    image: nginx:latest
    container_name: pharmacy_nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - app
    networks:
      - pharmacy_net

  db:
    image: mysql:5.7
    container_name: pharmacy_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shutterseek
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - pharmacy_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pharmacy_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "8081:80"
    networks:
      - pharmacy_net

networks:
  pharmacy_net:

volumes:
  db_data: